sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
branches:
  only:
    - master
after_script:
  - '[ ${TRAVIS_EVENT_TYPE} != "pull_request" ] && [ ${TRAVIS_BRANCH} = "master" ] && bundle exec codeclimate-test-reporter'
